### ISSUE TITLE
custom item size

### ISSUE THREAD

**Issue by Chakery** [KelvinJin/AnimatedCollectionViewLayout#13]
How to customize item size？（eg: `LinearCardAttributesAnimator`）

**Comment by jppgks** [comment]
```swift
LinearCardAttributesAnimator(minAlpha: 0.5, itemSpacing: 0.2, scaleRate: 0.9)
```

**Comment by KelvinJin** [comment]
@dipkasyap You can create your own animator based on the `LinearCardAttributesAnimator`.
