### ISSUE TITLE
Instead of zooming out the current cell in Page Animator, is it possible to Zoom In the next cell?

### ISSUE THREAD

**Issue by GodricG** [KelvinJin/AnimatedCollectionViewLayout#16]
So as you swipe out the current cell, the next cell zooms into place. Is something like this possible?

**Comment by KelvinJin** [comment]
Hmm, I think it's already there isn't it? In the current implementation of [ZoomInOutAttributesAnimator](https://github.com/KelvinJin/AnimatedCollectionViewLayout/blob/master/Source/ZoomInOutAttributesAnimator.swift), the current cell will be zoomed out and the next cell will be zoomed in. You can change the parameters and make it more obvious i guess.

**Comment by GodricG** [comment]
I am looking to use the [PagesAttributesAnimator](https://github.com/KelvinJin/AnimatedCollectionViewLayout/blob/master/Source/PageAttributesAnimator.swift). Is it possible to apply the animation to the next cell instead of the current cell? Something like this: [Inshorts-test](https://github.com/vikrantsharma123/ios-inshorts-view)

**Comment by KelvinJin** [comment]
@GodricG Sorry for the late reply (Was on a trip...)

Yep, you can definitely achieve that easily by using the following custom animator:

```Swift
/// An animator that slides away the current cell while zoom in the next cell.
struct PageOutAttributesAnimator: LayoutAttributesAnimator {
    /// The max scale that would be applied to the current cell. 0 means no scale. 0.2 by default.
    public var scaleRate: CGFloat
    
    public init(scaleRate: CGFloat = 0.1) {
        self.scaleRate = scaleRate
    }
    
    public func animate(collectionView: UICollectionView, attributes: AnimatedCollectionViewLayoutAttributes) {
        let position = attributes.middleOffset
        let contentOffset = collectionView.contentOffset
        let itemOrigin = attributes.frame.origin
        
        if position > 0 {
            let scaleFactor = -scaleRate * position + 1.0
            let transform = CGAffineTransform(scaleX: scaleFactor, y: scaleFactor)
            attributes.transform = transform.concatenating(CGAffineTransform(translationX: contentOffset.x - itemOrigin.x, y: contentOffset.y - itemOrigin.y))
        }
        
        attributes.zIndex = Int.max - attributes.indexPath.row
    }
}
```

You might need to tweak the parameters to suit your needs.

**Comment by GodricG** [comment]
Just what I was looking for. Works beautifully. Thanks a lot for this @KelvinJin. So basically when I check the position > 0, it applies the transform to the next card?

**Comment by KelvinJin** [comment]
That's correct:)

**Comment by pixelbendr** [comment]
It works perfect for me too, However I want the cards to stack showing the first and second cell on initialisation. Please how can I achieve this?
