### ISSUE TITLE
CubeAttributesAnimator Not Working

### ISSUE THREAD

**Issue by mbariscicek** [KelvinJin/AnimatedCollectionViewLayout#17]
Firstly thank you for this library, exactly what i need is the library :) I tried all of Attributes Animators, they all working well but CubeAttributesAnimator not working.

**Comment by KelvinJin** [comment]
Hmm, can you provide a sample project to demonstrate the issue? I need more information on this.

**Comment by yukitoto** [comment]
I encountered this issue too.

**Comment by yukitoto** [comment]
This is very simple sample project.
[CubeAnimationSample.zip](https://github.com/KelvinJin/AnimatedCollectionViewLayout/files/1184658/CubeAnimationSample.zip)

**Comment by yukitoto** [comment]
@KelvinJin What cause this bug?

**Comment by yukitoto** [comment]
This is storyboard version.
[CubeAnimationSample 2.zip](https://github.com/KelvinJin/AnimatedCollectionViewLayout/files/1184663/CubeAnimationSample.2.zip)

**Comment by yukitoto** [comment]
This bug of non-storyboard is fixed if I use contentView of UICollectionView.

**Comment by KelvinJin** [comment]
@yukitoto Hey, thanks for the sample project. Yeah, the issue is the contentView. The CubeAttributesAnimator will only transform `contentView` of the `UICollectionViewCell`, which means  the background colour of the cell has to be clear (or all the same for all cells) in order for it to make sense. You can, however, change the background colour of the contentView!

I'll have to document this somewhere...

**Comment by boominadhaprakash** [comment]
@KelvinJin I am unable to understand, how to add the CubeAttributesAnimator to contentView of cell.
I am not using Storyboard or XIB. I have added the AnimatedCollectionViewLayout as UICollectionViewLayout Programmatically. But not working. Can you please assist me?

**Comment by boominadhaprakash** [comment]
@KelvinJin I have fixed by adding the all subviews inside the cell.ContentView. previously I have added to cell subview. I unable to catch the previous comment points. I got the issue. :)
