### ISSUE TITLE
Animators folder not installed with CocoaPods

### ISSUE THREAD

**Issue by mhergon** [KelvinJin/AnimatedCollectionViewLayout#2]
Hi,

When I install the library with `CocoaPods` the `Animators` folder is missing.

<img width="241" alt="captura de pantalla 2017-02-17 a las 0 17 07" src="https://cloud.githubusercontent.com/assets/621373/23045844/a6038b38-f4a6-11e6-85a3-db23b6c7cb5f.png">

I tried `pod deintegrate`, `pod update` and `pod install` many times but nothing works.

Thanks!

**Comment by KelvinJin** [comment]
@mhergon Hey, sorry for that. Apparently I'm not that familiar with Cocoapods. This has been fixed in 0.1.2.

**Comment by mhergon** [comment]
Thanks!
