### ISSUE TITLE
Can`t use with Cocoapods

### ISSUE THREAD

**Issue by comeonyoh** [KelvinJin/AnimatedCollectionViewLayout#23]
![screenshot](https://cloud.githubusercontent.com/assets/4162456/26522288/d6a33e3e-4337-11e7-8f07-2be49bcc12f3.png)

Thanks to your nice library. 

But cannot use with Cocoapods...

is it a temporary problem or not use with Cocoapods?

**Comment by KelvinJin** [comment]
try `pod repo update` first and then `pod install`.
