### ISSUE TITLE
There is a question about the position parameter in the delegate

### ISSUE THREAD

**Issue by broccolii** [KelvinJin/AnimatedCollectionViewLayout#3]
If I set the width and spacing of the CollectionItem, then how do I calculate the position parameter in the Delegate I need to modify the original code logic if there is a better way to deal with this ?

**Comment by broccolii** [comment]
Sorry, I just saw the README TODO content, expect to give a perfect solution

**Comment by KelvinJin** [comment]
Hey @broccolii, this is a good question! I'm also trying to find the best way to support such scenario.

Two cases pop up in my mind:

+ Each item (including the spacing between items) takes a fullscreen space.
+ Each item (including the spacing between items) takes part of the screen. So you'd have two or more visible items at the same time. 

In the first scenario, it's still reasonable to have animations such as CrossFade or ZoomInOut but not Cube for instance. However, the second scenario makes even CrossFade inappropriate. (Cards might still be alright though.)

What type of scenario are you looking for?

**Comment by broccolii** [comment]
@KelvinJin 
I see  [FSPagerViewTransformer](https://github.com/WenchaoD/FSPagerView) in `FSPagerView` when found to be a good solution, so I made some [changes](https://github.com/broccolii/FSPagerView/blob/master/FSPagerView/FSPageViewTransformer.swift), honestly I think the definition of the parameters here is not easy to understand, so I mentioned this in the [pull request](https://github.com/WenchaoD/FSPagerView/pull/6). Although it is not a good solution, but it is useful

**Comment by KelvinJin** [comment]
@broccolii Yeah, for a complicated animation, the parameters will be hard to define. IMHO, the library should give you the ability to customise the animation by providing enough contexts.

I'm planning to add more context information into the `UICollectionViewLayoutAttributes`. For instance, the scroll direction, the distance between the centre of the item and the centre of the collectionView, the distance between the top of the item and the top of the collectionView and the distance between the bottom of the item and the bottom of the collectionView. With all the information, you can create your own animations such as **slide in** when you scroll the list.
