### ISSUE TITLE
XCode 10 GM and Swift 4.2 support fails to compile

### ISSUE THREAD

**Issue by jlaws** [KelvinJin/AnimatedCollectionViewLayout#43]
AnimatedCollectionViewLayout.swift:78:33: 'UICollectionViewScrollDirection' has been renamed to 'UICollectionView.ScrollDirection'

**Comment by KelvinJin** [comment]
Xcode 10 with Swift 4.2 support is now released. Thanks for submitting the issue!

**Comment by jlaws** [comment]
Works great, thank you!
