### ISSUE TITLE
How can we make this?

### ISSUE THREAD

**Issue by invisible66** [KelvinJin/AnimatedCollectionViewLayout#46]
The firstly, sorry for title :)

Can we make like this?

![68747470733a2f2f662e666c6f636b75736572636f6e74656e74322e636f6d2f353434626562663135303736343632333334613663306637](https://user-images.githubusercontent.com/8086679/53096066-4cd0d400-352f-11e9-9c13-a6eed055d02f.gif)

**Comment by KelvinJin** [comment]
The gif only shows 3 items. I wonder how it will work if there're more than 3 in the list.

**Comment by gsbernstein** [comment]
I think this kind of thing is possible with custom animation layouts but I haven't had a lot of luck with controlling the z-axis for overlapping.

**Comment by invisible66** [comment]
@KelvinJin I think it will be show 3 item if there're more than 3..

**Comment by invisible66** [comment]
Hey guys, to be honest, I copied the gif from [Gravity Slider](https://github.com/ApplikeySolutions/GravitySlider). This library is good but not useful.. In gravity slider, you can't set index programmatically and you can't find current index.. And if you change cell size, animation going worse. So if you can add a new animation type like gif, it will be perfect.. if not I will use "LinearCard" animation :)

**Comment by KelvinJin** [comment]
@invisible66  

> you can't set index programmatically and you can't find current index

I don't really understand what this means sorry. 

Give the following animator a try and let me know how you like it. Play around with these parameters as well to make sure the animation works best for your scenario.

```
import Foundation

public struct SwapOutAttributesAnimator: LayoutAttributesAnimator {
    
    private let maxWidthRadio: CGFloat
    private let minDistanceRadio: CGFloat
    private let scaleRate: CGFloat
    
    public init(maxWidthRadio: CGFloat = 0.7, minDistanceRadio: CGFloat = 0.5, scaleRate: CGFloat = 0.5) {
        self.maxWidthRadio = maxWidthRadio
        self.minDistanceRadio = minDistanceRadio
        self.scaleRate = scaleRate
    }
    
    public func animate(collectionView: UICollectionView, attributes: AnimatedCollectionViewLayoutAttributes) {
        let position = attributes.middleOffset
        
        // guard let contentView = attributes.contentView else { return }
        let contentOffset = collectionView.contentOffset
        let period = CGFloat.pi - asin(minDistanceRadio / maxWidthRadio)
        
        attributes.frame = CGRect(origin: contentOffset, size: attributes.frame.size)
        
        switch Double(position) {
        case -2.0...2.0:
            let offsetFromCenter = CGFloat(sin(period * position))
             let translationTransform: CGAffineTransform
            if attributes.scrollDirection == .horizontal {
                let offset = offsetFromCenter * maxWidthRadio * collectionView.bounds.width
                translationTransform = CGAffineTransform(translationX: offset, y: 0)
            } else {
                let offset = offsetFromCenter * maxWidthRadio * collectionView.bounds.height
                translationTransform = CGAffineTransform(translationX: 0, y: offset)
            }

            let scaleFactor = max(scaleRate - 0.2 * abs(position), 0.0)
            let scaleTransform = CGAffineTransform(scaleX: scaleFactor, y: scaleFactor)
            attributes.transform = translationTransform.concatenating(scaleTransform)
            
            let zIndex = -pow(abs(position), 2.0) + 1.0
            attributes.zIndex = Int(zIndex * 1000)
            attributes.alpha = 1
        default:
            attributes.alpha = 0
        }
    }
}
```

**Comment by invisible66** [comment]
> 
> > you can't set index programmatically and you can't find current index
> 
> I don't really understand what this means sorry.

Gravity Slider library using `UICollectionView`. If you want to change item in code, you can't do this. Sorry for my bad English :)
