### ISSUE TITLE
Version for Swift 2.3?

### ISSUE THREAD

**Issue by waseefakhtar** [KelvinJin/AnimatedCollectionViewLayout#5]
I tried 0.1.2 on Swift 2.3 and apparently I get errors. Is there a version supported by Swift 2.3?

**Comment by KelvinJin** [comment]
@waseefakhtar Not at the moment. I'll see what i can do about that. Should be pretty easy to support Swift 2.3.

**Comment by KelvinJin** [comment]
Sorry. Given Xcode no longer supports Swift 2.3, I'll not put effort in supporting it as well. Thanks for the understanding.
