### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by kgn** [KelvinJin/AnimatedCollectionViewLayout#6]
In addition to CocoaPods it would be great to be able to include this project via [Carthage](https://github.com/Carthage/Carthage).

**Comment by KelvinJin** [comment]
I'm not really familiar with Carthage in general. Would be good to make travis generate the prebuilt version automatically if possible.

**Comment by btc** [comment]
It presently works with Carthage. However, there is one minor problem. When installed via Carthage, the minimum deployment target is 10.1. I have opened an issue for this. See #12

**Comment by BilalReffas** [comment]
Carthage works fine as @btc mentioned it needs to change the deployment target that's it. Maybe I should create a pull request?

**Comment by KelvinJin** [comment]
fixed in 0.3.0.
