### ISSUE TITLE
Cell scroll with scrollToItem does not work

### ISSUE THREAD

**Issue by soring323** [KelvinJin/AnimatedCollectionViewLayout#62]
ScrollToItem function is working well in UICollectionViewFlowLayout but after implement this layout it does not work. 
Hint. 
When viewcontroller is loaded, in viewDidLayoutSubviews cycle, it is working.

**Comment by soring323** [comment]
tested 1.01 and latest version layout already!

**Comment by updev0612** [comment]
when disable collecitonView pagination, it is working but if I set pagenation is enable, it does not work

**Comment by soring323** [comment]
yeah. it is working but it is not solution for me. I have to use pagination function. 
I've just found solution. 
Thanks for your advice!

**Comment by yunustek** [comment]
How did you solve it?

> yeah. it is working but it is not solution for me. I have to use pagination function.
> I've just found solution.
> Thanks for your advice!

How did you solve it?

**Comment by yessenali** [comment]
> yeah. it is working but it is not solution for me. I have to use pagination function. I've just found solution. Thanks for your advice!

How did you solve it?
