### ISSUE TITLE
Animator folder did not included

### ISSUE THREAD

**Issue by heuism** [KelvinJin/AnimatedCollectionViewLayout#7]
Do i need to copy the Animator folder or did i do something wrong that the code can not recognized the animator? Even though i see in your commit message that you fixed the issue the pod didn't include the animator? Thank @KelvinJin

**Comment by KelvinJin** [comment]
Hey @heuism! I think the latest version 0.1.2 fixed this problem. I did a simple test the other day. You might need to do `pod update AnimatedCollectionViewLayout` if you have an old version.

You can also find the version of the current pod by running `pod install` again.

**Comment by heuism** [comment]
To be honest, i just install the pod today. So if in that case it is weird. I may try the install again:). Will reply you after i did that :)

**Comment by heuism** [comment]
i say here that:
```
Analyzing dependencies
Downloading dependencies
Using AnimatedCollectionViewLayout (0.1.1)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
```

So seem like it is still in 0.1.1 after i install it.

**Comment by KelvinJin** [comment]
@heuism i think i know the problem. As you can see that the [0.1.2](https://github.com/CocoaPods/Specs/blob/master/Specs/b/7/6/AnimatedCollectionViewLayout/0.1.2/AnimatedCollectionViewLayout.podspec.json) has been pushed to CocoaPods master repo a few days ago.

You need to update the CocoaPods local repo by doing `pod repo update` and then reinstall/update the pod.

Let me know if this helps ;)

**Comment by heuism** [comment]
Thanks for your help. The issues was solved when i see "Installing..." :)

Btw, i followed the manual but the layout doesn't snap and full screen as yours i wonder why :). I will ask you more in another thread. This one is finished.

Thanks again @KelvinJin
